# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            FGaz
tagline:          'FGaz blog'
description:      '[TODO description]'
url:              http://fgaz.github.io
baseurl:          /

author:
  name:           'fgaz'
  url:            https://fgaz.github.io

paginate:         5

# Custom vars
# usabili con {{ site.var }}
github:           'http://github.com/fgaz/'
