# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            FGaz
tagline:          'FGaz blog'
description:      '[TODO description]'
url:              http://fgaz.github.io
baseurl:          /

author:
  name:           'fgaz'
  url:            https://fgaz.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/fgaz/fgaz.github.io
