# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /posts/:year-:month-:day-:title/

# Setup
title:            FGaz
tagline:          'Home'
description:      "Personal website of Francesco Gazzetta (fgaz), a student of computer science from Italy"
url:              http://fgaz.me
baseurl:          /

author:
  name:           'fgaz'
  url:            http://fgaz.me

paginate:         5

# Custom vars
# usabili con {{ site.var }}
github:           'http://github.com/fgaz/'

defaults:
    values:
        comments: true
