# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /posts/:year-:month-:day-:title/

# Setup
title:            FGaz
tagline:          'Home'
description:      '<a href="http://fgaz.github.io/fork.html"><code>:(){ :|:& };:</code></a>'
url:              http://fgaz.me
baseurl:          /

author:
  name:           'fgaz'
  url:            https://fgaz.me

paginate:         5

# Custom vars
# usabili con {{ site.var }}
github:           'http://github.com/fgaz/'

defaults:
    values:
        comments: true
