base_url = "https://fgaz.me"

title = "fgaz"
description = "I am a student of computer science. I build things, and sometimes write here"
default_language = "en"

highlight_code = true
generate_rss = true
compile_sass = true

[extra]
github = "https://github.com/fgaz"

