base_url = "https://fgaz.me"

title = "fgaz"
description = "I am a student of computer science. I build things, and sometimes write here"
default_language = "en"

highlight_code = false
generate_rss = true
compile_sass = true

[extra]
copyright_holder = "Francesco Gazzetta"
license = "" # temporary all rights reserved until I decide a foss license
color = "#6a9fb5"
github = "https://github.com/fgaz"

